### ISSUE TITLE
Features and documentation ?

### ISSUE THREAD

**Issue by Rezrazi** [nikoma/apphera-core#2]
Hey,
I'm looking to get more information about your project, but unfortunately the documentation and features are non existent on the repo, and the website https://www.apphera.com/ is unreachable.

**Comment by nikoma** [comment]
Hi, we are in the progress of rolling this project into a new project. It's at https://github.com/nikoma/webwithoutborders
It might take a few more weeks.

**Comment by byte-ma** [comment]
> Hi, we are in the progress of rolling this project into a new project. It's at https://github.com/nikoma/webwithoutborders It might take a few more weeks.

can not access this
